package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF24389C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF3F51B5)
val onPrimaryContainerLight = Color(0xFFCACFFF)
val secondaryLight = Color(0xFF006A60)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF85F6E5)
val onSecondaryContainerLight = Color(0xFF007166)
val tertiaryLight = Color(0xFF6C3400)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF8F4700)
val onTertiaryContainerLight = Color(0xFFFFC7A2)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8F9FF)
val onBackgroundLight = Color(0xFF0B1C30)
val surfaceLight = Color(0xFFF8F9FF)
val onSurfaceLight = Color(0xFF0B1C30)
val surfaceVariantLight = Color(0xFFD3E4FE)
val onSurfaceVariantLight = Color(0xFF454652)
val outlineLight = Color(0xFF757684)
val outlineVariantLight = Color(0xFFC5C5D4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF213145)
val inverseOnSurfaceLight = Color(0xFFEAF1FF)
val inversePrimaryLight = Color(0xFFBAC3FF)
